# Generated by Django 3.1 on 2022-04-24 09:57

from django.db import migrations, models
import searchbar.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('videofile', models.FileField(upload_to='videos/', validators=[searchbar.validators.validate_video])),
            ],
        ),
    ]
