# Generated by Django 3.1 on 2022-04-25 17:00

from django.db import migrations, models
import searchbar.validators


class Migration(migrations.Migration):

    dependencies = [
        ('searchbar', '0005_auto_20220425_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='', validators=[searchbar.validators.validate_video]),
        ),
    ]
